### ISSUE TITLE
Lack of a license

### ISSUE THREAD

**Issue by lebriton** [nichochar/CLHN#3]
I maintain an [awesome](https://github.com/topics/awesome) list named [awesome-hackernews](https://github.com/bminusl/awesome-hackernews) where Hacker News related tools are featured.

I noticed `CLHN` does not have a license. See [https://choosealicense.com/no-permission/](https://choosealicense.com/no-permission/).

Is this an oversight?

**Comment by nichochar** [comment]
Good point! I just added an MIT license for this.
